<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-09T21:51:58 AEDT" name="Suite" finished-at="2024-01-09T21:52:09 AEDT" duration-ms="10293">
    <groups>
    </groups>
    <test started-at="2024-01-09T21:51:58 AEDT" name="Test" finished-at="2024-01-09T21:52:09 AEDT" duration-ms="10293">
      <class name="com.mannautomation.test.HomePageClickOnItemWithMaxPrice">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.mannautomation.test.HomePageClickOnItemWithMaxPrice@3daa422a]" started-at="2024-01-09T21:51:58 AEDT" name="setUp" finished-at="2024-01-09T21:52:02 AEDT" duration-ms="3583" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="findItemWithMaxPrice()[pri:0, instance:com.mannautomation.test.HomePageClickOnItemWithMaxPrice@3daa422a]" started-at="2024-01-09T21:52:02 AEDT" name="findItemWithMaxPrice" finished-at="2024-01-09T21:52:06 AEDT" duration-ms="4080" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findItemWithMaxPrice -->
      </class> <!-- com.mannautomation.test.HomePageClickOnItemWithMaxPrice -->
      <class name="com.mannautomation.test.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.mannautomation.test.LoginTest@6c80d78a]" started-at="2024-01-09T21:52:06 AEDT" name="setUp" finished-at="2024-01-09T21:52:07 AEDT" duration-ms="980" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginWithEmailAndPassword()[pri:0, instance:com.mannautomation.test.LoginTest@6c80d78a]" started-at="2024-01-09T21:52:07 AEDT" name="loginWithEmailAndPassword" finished-at="2024-01-09T21:52:09 AEDT" duration-ms="1607" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.mannautomation.test.LoginTest.loginWithEmailAndPassword(LoginTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithEmailAndPassword -->
      </class> <!-- com.mannautomation.test.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
